App issues
yieldi-labs/yieldi-web pull request #29
Opened 2024-11-11 19:05 UTC by sstefdev

2024-11-11 22:36 UTC, MattNguyen requested changes
can you also run `pnpm lint:fix` please

2024-11-11 22:36 UTC, MattNguyen commented on app/app/components/modals/Wallet/ChainSelector.tsx
> +          label={selectedChain.length !== 9 ? "select" : "deselect all"}
titlecase please

2024-11-11 22:36 UTC, MattNguyen commented on app/app/modal.tsx
> +        className="bg-neutral-100 backdrop-blur-md border-4 border-white h-[95vh] relative z-20 max-w-lg w-[95%] mx-auto rounded-xl p-7 overflow-y-auto"
why h-95vh? makes the modal look pretty tall on large displays. prefer if this was max height but maybe we just take it out

2024-11-11 22:36 UTC, MattNguyen commented on app/hooks/useWalletConnection.ts
> +        const identifier = chainIdentifiers["solana"];
seems like a mistake hardcoding `solana` here?

2024-11-20 06:04 UTC, MattNguyen commented
@sstefdev 

phantom still appears as detected even though i have it disabled

<img width="796" alt="image" src="https://github.com/user-attachments/assets/88dddd4a-1628-4117-8dd7-97ac7cccfc7a">

2024-11-20 06:06 UTC, MattNguyen commented
After I connect with WalletConnect, the WalletConnect qr code modal closes but nothing happens.

Get this in the dev console:

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/720454ec-2cfe-49a8-84e6-951d0b873fcc">

2024-11-20 06:08 UTC, MattNguyen commented
Have you verified vulticonnect works with thorchain on a local build of vulticonnect? https://github.com/vultisig/vulticonnect/pull/71 hasn't been merged so we shouldn't disable it for now until it's released to public.

2024-11-21 05:47 UTC, sstefdev commented
> Have you verified vulticonnect works with thorchain on a local build of vulticonnect? [vultisig/vulticonnect#71](https://github.com/vultisig/vulticonnect/pull/71) hasn't been merged so we should disable vultisig<>thorchain for now until it's released to public.

Yes I have tested it with the PR version that it was shared with us, but I will remove it till it is stable version

2024-11-21 05:55 UTC, sstefdev commented
> @sstefdev
> 
> phantom still appears as detected even though i have it disabled
> 
> <img alt="image" width="796" src="https://private-user-images.githubusercontent.com/1606774/387960543-88dddd4a-1628-4117-8dd7-97ac7cccfc7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjgyNzAsIm5iZiI6MTczMjE2Nzk3MCwicGF0aCI6Ii8xNjA2Nzc0LzM4Nzk2MDU0My04OGRkZGQ0YS0xNjI4LTQxMTctOGRkNy05N2FjN2NjY2ZjN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDU0NjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ3OTI3OWJjNTRkZjk2Y2U1OWM0OTg3Y2JhZWRlYzY1Yjg5MWY5ODlmZDQ2ZTAwZDU3MDdlYTNiMTM0NDVmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5H0tJxpJdtpmzyHZqhGnICRw2wnqYlfjeQsK0PDSHT8">

@MattNguyen please pull the latest changes and try again

2024-11-21 10:13 UTC, sstefdev commented
> After I connect with WalletConnect, the WalletConnect qr code modal closes but nothing happens.
> 
> Get this in the dev console:
> 
> <img alt="image" width="1064" src="https://private-user-images.githubusercontent.com/1606774/387961421-720454ec-2cfe-49a8-84e6-951d0b873fcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODQyNDUsIm5iZiI6MTczMjE4Mzk0NSwicGF0aCI6Ii8xNjA2Nzc0LzM4Nzk2MTQyMS03MjA0NTRlYy0yY2ZlLTQ5YTgtODRlNi05NTFkMGI4NzNmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMTAxMjI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTIwMzc3MTE0Y2JhYWEzYjAwODYxOGRkZmJiNmU2MjdhMGNmNWVlMjdiYzc0MmE2OWY2MjY2MTlhNDMxOTNjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.z0pqjRRJZdE-gz0VhcQWMy5cKMi61cqwUBOglfPaKCw">

This is now fixed again with the latest changes

2024-11-21 17:18 UTC, MattNguyen approved these changes

2024-11-21 17:18 UTC, merged